name: ci
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x      
      - run: pip install --upgrade pip
      - run: pip install mkdocs-material
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-encryptcontent-plugin
      - run: pip install mkdocs-git-revision-date-plugin
      - run: mkdocs gh-deploy --force
      # C'est ici qu'il faut ajouter si besoin
      # les instructions pour installer avec pip
      # les autres plugins MkDocs ou extensions MarkDown
      # souhaités pour le déploiement du site...
